name: Metrics

on:
  push: {branches: ["main"]}

jobs:

  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          base: header
          filename: header.svg
          token: ${{ secrets.METRICS_TOKEN }}

  repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          base: repositories
          filename: repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
